(setq *tasks*
    '(
        (purchase_lot 2)
        (design_house 5)
        (get_permit 1 purchase_lot design_house)
        (get_bids 14 purchase_lot design_house) 
        (select_subs 2 get_bids)
        (excavate 1 get_permit select_subs) 
        (construct_basement 7 excavate)
        (order_windows_doors 3 purchase_lot design_house) 
        (get_windows_doors 10 order_windows_doors)
        (frame 12 get_permit select_subs) 
        (rough_plumbing 5 frame)
        (rough_electric 3 frame)
        (roof 4 frame)
        (install_windows_doors 7 get_windows_doors rough_plumbing rough_electric)
        (vapor_barrier_insulation 2 roof install_windows_doors)
        (drywall 5 vapor_barrier_insulation)
        (inside_paint 3 drywall)
        (cupboards 3 inside_paint)
        (carpet_floor 5 inside_paint)
        (lights 2 inside_paint)
        (plumbing_heating 6 inside_paint)
        (siding 2 roof install_windows_doors)
        (outside_paint 3 siding)
        (move_house 1 cupboards carpet_floor lights plumbing_heating outside_paint)
        (connections 2 construct_basement move_house)
        (landscape 4 construct_basement move_house)
        (move_in 0 landscape connections)
    )
)
